syntax = "proto3";

option csharp_namespace = "Basket.API";

package basket;

service GrpcBasketService {
  rpc GetBasket (GetBasketRequest) returns (BasketResponse);
  rpc UpdateBasket (UpdateBasketRequest) returns (BasketResponse);
  rpc DeleteBasket (DeleteBasketRequest) returns (DeleteBasketResponse);
}

message GrpcBasketItem {
  string id = 1;
  string name = 2;
  double unitPrice = 3;
  int32 quantity = 4;
  string pictureUri = 5;
}

message UpdateBasketRequest {
  string customerId = 1;
  repeated GrpcBasketItem items = 2;
}

message GetBasketRequest {
  string customerId = 1;
}

message DeleteBasketRequest {
  string customerId = 1;
}

message DeleteBasketResponse {
  bool success = 1;
}

message BasketResponse {
  string customerId = 1;
  repeated GrpcBasketItem items = 2;
}